### ISSUE TITLE
.min.js

### ISSUE THREAD

**Issue by Opadera** [ljagis/leaflet-measure#107]
the old version had a leaflet-measure.min.js which is not there currently. It convienently had all the functionality in one file (inlcuding languages). Can you add that or tell me how to do it myself?

**Comment by brandoncopeland** [comment]
Sure. The builds are available from npm. You can install with `npm i leaflet-measure`. You can also clone the repository and run `yarn build`. This will build a `dist` directory with `leaflet-measure.js` and `leaflet-measure.css`. Each language is now built into a separate JavaScript file, so you will need to use `leaflet-measure.hu.js` instead of `leaflet-measure.js` for Hungarian.
