### ISSUE TITLE
size of icon

### ISSUE THREAD

**Issue by DrYSG** [ljagis/leaflet-measure#19]
A very very minor aesthetic point. It seems that all the other plug-ins that I have that show an icon, are 26px x 26px. So this one sticks out. I tried this code and it seems to work. What do you think about standardizing the size?

```
    .leaflet-control-measure .leaflet-control-measure-toggle, .leaflet-control-measure .leaflet-control-measure-toggle:hover {
        display: block;
        width: 26px;
        height: 26px;
        background-position: 50% 50%;
        background-repeat: no-repeat;
        background-image: url(images/rulers.png);
        border-radius: 5px;
        text-indent: 100%;
        white-space: nowrap;
        overflow: hidden;
    }
```

**Comment by ismyrnow** [comment]
The control button looks to be 26x26 for me. I'm using Chrome 47 on Windows 8.

**Comment by brandoncopeland** [comment]
@DrYSG Do you have an example of a plugin sized 26 x 26?

It looks like maybe Mapbox.js controls are 26 x 26 -  https://github.com/mapbox/mapbox.js/blob/v2.2.2/theme/style.css#L410.
But I think the 36 x 36 size matches the current Leaflet style -  https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L306.

I would like to match the Leaflet source where possible. Mapbox.js is popular enough, that I think also adding a Mapbox specific theme to this project would be cool. This would include resizing control toggles to the smaller 26 x 26 size. Otherwise, users can include their own stylesheet in projects using leaflet-measure to size any way they like.
