### ISSUE TITLE
add a point on a created layer

### ISSUE THREAD

**Issue by badreal** [ljagis/leaflet-measure#25]
After clicking on finish measurement and the layer created , if a new measurement is created and a point is placed inside the created feature, it shows the information window instead of adding a new point. The same happens if external layers are added to the map.

A way to handle that is to get the measure start event , then catch layer click and simulate a map click :

    map.fireEvent('click', {
      latlng: latlngPoint,
      layerPoint: map.latLngToLayerPoint(latlngPoint),
      containerPoint: map.latLngToContainerPoint(latlngPoint)
    });

I tried that on handling click on my layers and it works .

**Comment by brandoncopeland** [comment]
This is a known issue that needs a good solution.

1. One option is to create a transparent marker that always follows the mouse and is used to catch click events (instead of the map). With a high enough `zIndexOffset`, the marker would always be on top of all other layers. There would be a problem with this solution on touch devices since there is no mouse move to follow. Otherwise, I think its pretty good.

2. Another option is to temporarily disable click events on all other layers while measuring. I feel like this could get very messy, but it is doable I think.

You solution is similar to number 2 I think. Instead of disabling click events, you are suggesting triggering an additional map click event. This probably has similar messiness as number 2. Ideally though, the original handler should not fire. That way no popup or other side effects occur - only a new measure point.

I am very much open to any other solutions.

**Comment by brandoncopeland** [comment]
`measurestart`, `measureend` added at commit 2a383db.
