### ISSUE TITLE
I cant build measure over map elements.

### ISSUE THREAD

**Issue by Kopleman** [ljagis/leaflet-measure#54]
For example i have circles on my map, and  I cant set.continue measure line inside it. Any way to solve this?

**Comment by envirospatial** [comment]
Hi Kopleman,

I noticed the same issue.  I check my code and noticed that the map pane than contains my geoJson  layer zIndex property was set at 680.  I lowered it to 250 and it works fine.

**Comment by Kopleman** [comment]
Doesnt work for me becouze all html elements(circles and plugin's svgs) lay in same div

**Comment by brandoncopeland** [comment]
When a measurement is started, a marker with `z-index` of 1000  is placed on the map, and click events on that marker are used to add new points to the measurement. The z-index is set to ensure this marker is "above" all other elements. Is that not the case in your situation? Are other elements receiving the click event instead? What are their z-indexes?

**Comment by Kopleman** [comment]
![2017-03-01_09-49-42](https://cloud.githubusercontent.com/assets/3992563/23448987/381fa200-fe65-11e6-933a-3ffb434647fa.png)
At screen when the cursor over the red circle(L.Circle element) clicks are not registred.
The `<svg>` and its `<g>` dont have `z-index`.

**Comment by tomchadwin** [comment]
I'm having the same issue. I've used `captureZIndex: 10000`, but vertices are still not created if I click on a feature. The `pane` the feature is in has zIndex 602.

I'd really like to get a solution to this. I have used the a different Leaflet plugin for measurement in my qgis2web plugin. However, it has stopped working. I would like to switch to this plugin for Leaflet measurement functionality, but I hoped this issue was sorted.

Is there anything I can do to help try to fix this issue?

**Comment by brandoncopeland** [comment]
@Kopleman @tomchadwin Do you have an application demonstrating the issue that I can checkout? Or maybe recreate with a Plunker?

**Comment by brandoncopeland** [comment]
The general design if it helps troubleshoot.. When a measure is started, a marker 2X the size of the map is is added to the `leaflet-marker-pane` at the `captureZIndex` configured. The `leaflet-marker-pane` is the topmost leaflet pane, above the `leaflet-overlay-pane` containing vector layers.

Also, at what versions of Leaflet and leaflet-measure are you seeing this?

**Comment by tomchadwin** [comment]
Leaflet 1.0.3
leaflet-measure 2.1.7

Are zIndices local to Leaflet panes. I am creating a pane for each layer, the panes have zIndex 600 + n, n being a simple count of the layers in the map. In my example page, my layers are in panes with zIndices 600-602.

I can try to create a Plunker or equivalent, but the issue I have is that I am not writing the Leaflet code from scratch - qgis2web is writing it. It's therefore likely to be a bit more complex than you would like for a minimal example.

**Comment by tomchadwin** [comment]
OK, I see the issue now - the `leaflet-marker-pane` has `zIndex = 600`, so my map panes are higher. Let me see whether I am creating my new panes too high - I thought they were at an appropriate zIndex, but I probably misunderstood the Leaflet pane hierarchy.

**Comment by tomchadwin** [comment]
Confirmed: if I drop my panes down to 400 + n, measure clicks don't reveal feature popups. Apologies for the noise.

**Comment by tomchadwin** [comment]
Update: I was a little confused, when I changed my panes' zIndices to 400-2 that, although it was working, the measure lines were appearing *below* these layers. Investigating showed that the measure lines were appearing in the `leaflet-overlay-pane`, not the `leaflet-marker-pane`. Since that has `zIndex = 400`, we see the issue. Are you sure the measure lines are intended to appear in the pane?

**Comment by lailamt** [comment]
I'm working on a project and got the same issue with the measure tool. After read lots of threads of issues I fixed the problem changing `z-index` of the `leaflet-overlay-pane` class. Now it works fine in all browsers except IE... Don't know if it's the best solution though.
